name: Docker Image CI Dummy

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
    inputs:
      Dockerfile:
        description: 'Dockerfile'
        required: false
        default: 'Dockerfile'
      custom-config:
        description: 'custom-config'
        required: false
        default: 'qemu_x86_64_defconfig'

jobs:

  build:

    runs-on: ubuntu-22.04 #ubuntu-20.04 #ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        echo Dockerfile: ${{ inputs.Dockerfile }}
        echo custom-config: ${{ inputs.custom-config }}
        echo GITHUB_WORKSPACE: ${{ github.workspace }}
        echo GITHUB_REPOSITORY: ${{ github.repository }}
        echo GITHUB_ACTION_REPOSITORY: $GITHUB_ACTION_REPOSITORY
    - name: Build the Docker image
      #run: docker build . --file ${{ input.Dockerfile }} --tag my-image-name:$(date +%s)
      run: cd support/docker && docker build . --file Dockerfile --tag local
    - name: Run the docker image and make custom-config
      run: ls -l $PWD && docker run -it -v $PWD:/buildroot -w/srv local make ${{ inputs.custom-config }}

